### PR TITLE
agent: clean up socket and port file on SIGTERM and SIGQUIT

### PR DESCRIPTION
**Pull request by tklauser**
In case the agent is exiting due to a SIGTERM or SIGQUIT it is leaking
the port files in the gops config directory, as e.g. reported in
cilium/cilium#11455

Make sure the socket is cleaned up and port files in the gops config
directory are removed upon these signals by also relaying these signals
to the signal channel in gracefulShutdown. In case of SIGTERM, which is
the "normal" termination signal, exit the process with exit status 0.

### CODE REVIEW

**Comment by tklauser** [comment]
Not sure why the required circleci check still has status Expected, it seems to have been successful though: https://circleci.com/gh/google/gops/130

**Comment by rakyll** [comment]
@tklauser Would you be interested if I add you as a contributor to this repo? So you can restart CI and merge without our participation?

**Comment by tklauser** [comment]
> @tklauser Would you be interested if I add you as a contributor to this repo? So you can restart CI and merge without our participation?

@rakyll Sure, thank you! I'd be glad to help out.

**Comment by rakyll** [comment]
An invitation is sent! Thanks so much! Let me know if you need anything else.

**Comment by tklauser** [comment]
Awesome, thank you @rakyll!

**Comment by tklauser** [comment]
@rakyll sorry for bothering you again. Looks like there is still some issue with the circleci checks. I tried manually re-triggering them but the status still says _Waiting for status to be reported_. Looks like some changes in the GitHub settings may be needed: https://circleci.com/docs/2.0/workflows-waiting-status/

May I please ask you to quickly check whether the settings on the gops project correspond to the ones given in the circleci docs link? Thanks a lot!

**Pull request merged**
