### PR TITLE
vendor: sync 'vendor' dir with go.mod

### PR DESCRIPTION
**Pull request by pborzenkov**
The commit contains changes produced by 'go mod vendor' command. It
syncs the dependencies listed in `go.mod` file with the ones in
`vendor/` directory.

With this change `go build -mod=vendor` works again.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
Thanks for fixing this! Seems like I missed that in my last PRs updating the dependencies.

**Comment by pborzenkov** [comment]
@tklauser  Thanks for quick reply! Any chance you can cut a minor release with the fix?

**Comment by tklauser** [comment]
> @tklauser Thanks for quick reply! Any chance you can cut a minor release with the fix?

Sure, will cut a new release shortly.

**Comment by tklauser** [comment]
Tagged https://github.com/google/gops/releases/tag/v0.3.15. Thanks again @pborzenkov!

**Comment by pborzenkov** [comment]
Thanks!

**Pull request merged**
