### PR TITLE
Added command to display a tree of running Go processes

### PR DESCRIPTION
**Pull request by dastergon**
Implemented the `tree` command where users can list all running Go processes in a tree-like format (similar to pstree). The tree does not contain a root since the Go processes can be scattered around the process table.

Simple example:
```sh
$ gops tree
...
├── 1
│   └── 78818 (gocode) {go1.9}
├── 557
│   └── 635 (com.docker.supervisor) {go1.9.2}
│       └── 638 (com.docker.driver.amd64-linux) {go1.9.2}
└── 77987
    └── 86207 (gops) {go1.10}
```
Comparison with the plain gops command:
```sh
$ gops
78818 1     gocode                         go1.9   /Users/dastergon/golang/bin/gocode
86207 77987 gops                           go1.10  /Users/dastergon/golang/src/github.com/google/gops/gops
635   557   com.docker.supervisor          go1.9.2 /Applications/Docker.app/Contents/MacOS/com.docker.supervisor
638   635   com.docker.driver.amd64-linux  go1.9.2 /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux
```
Example output with a running agent:
```sh
$ gops tree
...
├── 1
│   └── 78818 (gocode) {go1.9}
├── 13744
│   └── [*]  77936 (hello) {go1.10}
├── 77987
│   └── 83140 (gops) {go1.10}
└── 557
    └── 635 (com.docker.supervisor) {go1.9.2}
        └── 638 (com.docker.driver.amd64-linux) {go1.9.2}
```
Comparison with the plain gops command:
```sh
$ gops
77936 13744 hello                        * go1.10  /Users/dastergon/golang/src/github.com/google/gops/examples/hello/hello
635   557   com.docker.supervisor          go1.9.2 /Applications/Docker.app/Contents/MacOS/com.docker.supervisor
83140 77987 gops                           go1.10  /Users/dastergon/golang/src/github.com/google/gops/gops
78818 1     gocode                         go1.9   /Users/dastergon/golang/bin/gocode
638   635   com.docker.driver.amd64-linux  go1.9.2 /Applications/Docker.app/Contents/MacOS/com.docker.driver.amd64-linux
```
The output could be enriched with more information about threads per-process, the path of the executable and more. In addition, the tree command could be expanded by filtering the branches by PPID, for instance: `gops tree 557`.

Please let me know if you have any suggestions!

### CODE REVIEW

**Comment by odeke-em** [comment]
@rakyll thanks for the ping, I'll merge this, I've tagged this for release `v0.3.4`.

Thank you again @dastergon!

**Comment by odeke-em** [comment]
Perhaps we should also document this in the README otherwise it'll be undiscovered.

**Comment by dastergon** [comment]
Hi @odeke-em,

In my commit, I have added a small section about `gops tree` in the README.

**Comment by odeke-em** [comment]
Yes in deed, I saw it but it hadn't stood out to me until I had to scroll down, thanks again!

**Pull request merged**
